import { CheckCircle2, Download, ExternalLink } from "lucide-react";
import { requireRole } from "@/lib/auth";
import { getAdminCompany } from "@/lib/services/admin";
import { PageHeader } from "@/components/ui/page-header";
import { StatusBadge } from "@/components/ui/status-badge";
import { CompanyProfileForm } from "@/components/forms/company-profile-form";
import { ApiActionButton } from "@/components/forms/api-action-button";
import { DecisionButtons } from "@/components/admin/decision-buttons";
import { formatDate, formatMoney } from "@/lib/constants";
import { ButtonLink } from "@/components/ui/button";

export default async function AdminCompanyDetailPage({ params }: { params: Promise<{ companyId: string }> }) {
  await requireRole("ADMIN"); const { companyId } = await params; const company = await getAdminCompany(companyId);
  const profile = { name: company.name, legalName: company.legalName, binIin: company.binIin, address: company.address, city: company.city, deliveryCities: company.deliveryCities, categories: company.categories, description: company.description, phone: company.phone, email: company.email, whatsapp: company.whatsapp, telegram: company.telegram, instagram: company.instagram, website: company.website, logoUrl: company.logoUrl, bannerUrl: company.bannerUrl };
  return <div className="grid gap-7"><PageHeader eyebrow="Карточка поставщика" title={company.name} description={`${company.legalName} · БИН ${company.binIin}`} actions={<><StatusBadge status={company.status} /><StatusBadge status={company.verificationStatus} /></>} />
    <div className="flex flex-wrap gap-2"><ApiActionButton endpoint={`/api/admin/companies/${company.id}/activate`} confirmMessage="Активировать компанию? Система повторно проверит документы, оплату и согласия."><CheckCircle2 className="size-4" />Активировать</ApiActionButton><DecisionButtons decisions={[{ endpoint: `/api/admin/companies/${company.id}/block`, label: "Заблокировать", kind: "reject", commentRequired: true, confirm: "Компания и её товары будут скрыты. Продолжить?" }]} />{company.website ? <a className="inline-flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold text-brand-800 hover:bg-brand-50" href={company.website} target="_blank" rel="noreferrer"><ExternalLink className="size-4" />Сайт</a> : null}</div>
    <details className="surface-flat" open><summary className="cursor-pointer list-none p-5 font-extrabold">Профиль компании</summary><div className="border-t p-5"><CompanyProfileForm company={profile} endpoint={`/api/admin/companies/${company.id}`} /></div></details>
    <section><h2 className="mb-3 text-lg font-extrabold">Документы</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Файл</th><th>Тип</th><th>Статус</th><th>Проверка</th><th></th></tr></thead><tbody>{company.documents.map((document) => <tr key={document.id}><td className="font-semibold">{document.originalName}</td><td>{document.type}</td><td><StatusBadge status={document.status} /></td><td><StatusBadge status={document.antivirusStatus} /></td><td><a className="inline-flex items-center gap-1 text-sm font-bold text-brand-800 hover:underline" href={`/api/admin/documents/${document.id}/download`}><Download className="size-4" />Скачать</a></td></tr>)}{company.documents.length === 0 ? <tr><td colSpan={5} className="text-center text-slate-500">Нет документов</td></tr> : null}</tbody></table></div></section>
    <section><h2 className="mb-3 text-lg font-extrabold">Счета и оплаты</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Счёт</th><th>Сумма</th><th>Счёт</th><th>Платёж</th><th>Дата</th></tr></thead><tbody>{company.payments.map((payment) => <tr key={payment.id}><td>{payment.invoice.invoiceNumber}</td><td>{formatMoney(payment.amount.toString(), payment.currency)}</td><td><StatusBadge status={payment.invoice.status} /></td><td><StatusBadge status={payment.status} /></td><td>{formatDate(payment.createdAt)}</td></tr>)}{company.payments.length === 0 ? <tr><td colSpan={5} className="text-center text-slate-500">Нет платежей</td></tr> : null}</tbody></table></div></section>
    <section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-extrabold">Товары</h2><ButtonLink href={`/admin/products/new?companyId=${company.id}`} variant="secondary">Добавить товар</ButtonLink></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Товар</th><th>Категория</th><th>Цена</th><th>Статус</th></tr></thead><tbody>{company.products.map((product) => <tr key={product.id}><td><a className="font-bold hover:text-brand-700" href={`/admin/products/${product.id}/edit`}>{product.name}</a><p className="text-xs text-slate-500">{product.sku}</p></td><td>{product.category.name}</td><td>{formatMoney(product.price.toString(), product.currency)}</td><td><StatusBadge status={product.status} /></td></tr>)}{company.products.length === 0 ? <tr><td colSpan={4} className="text-center text-slate-500">Нет товаров</td></tr> : null}</tbody></table></div></section>
    <section><h2 className="mb-3 text-lg font-extrabold">Журнал действий</h2><div className="table-wrap"><table className="data-table"><thead><tr><th>Дата</th><th>Администратор</th><th>Действие</th><th>Объект</th></tr></thead><tbody>{company.auditLogs.map((log) => <tr key={log.id}><td>{formatDate(log.createdAt)}</td><td>{log.adminUser.name}</td><td>{log.action}</td><td>{log.entityType} · {log.entityId.slice(0, 8)}</td></tr>)}{company.auditLogs.length === 0 ? <tr><td colSpan={4} className="text-center text-slate-500">Журнал пуст</td></tr> : null}</tbody></table></div></section>
  </div>;
}
