import { requireRole } from "@/lib/auth";
import { listAdminVerifications } from "@/lib/services/admin";
import { PageHeader } from "@/components/ui/page-header";
import { StatusBadge } from "@/components/ui/status-badge";
import { DecisionButtons } from "@/components/admin/decision-buttons";
import { ButtonLink } from "@/components/ui/button";
import { formatDate } from "@/lib/constants";

export default async function AdminVerificationsPage() {
  await requireRole("ADMIN"); const verifications = await listAdminVerifications();
  return <div className="grid gap-7"><PageHeader eyebrow="Trust & Safety" title="Верификации" description="Проверяйте документы и оплату по отдельности, затем принимайте решение по компании." />
    <div className="grid gap-5">{verifications.length ? verifications.map((verification) => <section key={verification.id} className="surface-flat p-5"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-extrabold">{verification.company.name}</h2><StatusBadge status={verification.status} /></div><p className="mt-1 text-sm text-slate-500">БИН {verification.company.binIin} · {verification.company.city} · отправлено {formatDate(verification.submittedAt)}</p></div><ButtonLink href={`/admin/company/${verification.companyId}`} variant="ghost">Карточка компании</ButtonLink></div>
      <div className="mt-5 table-wrap"><table className="data-table"><thead><tr><th>Документ</th><th>Тип</th><th>Антивирус</th><th>Статус</th><th>Действия</th></tr></thead><tbody>{verification.company.documents.map((document) => <tr key={document.id}><td><a className="font-semibold text-brand-800 hover:underline" href={`/api/admin/documents/${document.id}/download`}>{document.originalName}</a></td><td>{document.type}</td><td><StatusBadge status={document.antivirusStatus} /></td><td><StatusBadge status={document.status} /></td><td><DecisionButtons decisions={[{ endpoint: `/api/admin/documents/${document.id}/approve`, label: "Одобрить", kind: "approve" }, { endpoint: `/api/admin/documents/${document.id}/request-reupload`, label: "Перезагрузить", kind: "reupload", commentRequired: true }, { endpoint: `/api/admin/documents/${document.id}/reject`, label: "Отклонить", kind: "reject", commentRequired: true }]} /></td></tr>)}</tbody></table></div>
      <div className="mt-5 flex flex-col gap-4 rounded-xl bg-sand-50 p-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm font-bold">Оплата: <StatusBadge status={verification.company.payments[0]?.status ?? "PENDING"} /></p><p className="mt-1 text-xs text-slate-500">Тариф: {verification.company.subscriptions[0]?.plan.code ?? "не выбран"}</p></div>{verification.company.payments[0] ? <DecisionButtons decisions={[{ endpoint: `/api/admin/payments/${verification.company.payments[0].id}/confirm`, label: "Подтвердить оплату", kind: "approve", confirm: "Подтвердить оплату и активировать подписку?" }, { endpoint: `/api/admin/payments/${verification.company.payments[0].id}/reject`, label: "Отклонить оплату", kind: "reject", commentRequired: true }]} /> : null}</div>
      <div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t pt-5"><p className="text-sm font-bold">Итоговое решение по верификации</p><DecisionButtons decisions={[{ endpoint: `/api/admin/verifications/${verification.id}/approve`, label: "Одобрить", kind: "approve", confirm: "Одобрить верификацию компании?" }, { endpoint: `/api/admin/verifications/${verification.id}/request-reupload`, label: "Запросить документы", kind: "reupload", commentRequired: true }, { endpoint: `/api/admin/verifications/${verification.id}/reject`, label: "Отклонить", kind: "reject", commentRequired: true }]} /></div>
    </section>) : <div className="surface-flat p-10 text-center text-slate-500">Нет компаний, ожидающих проверки.</div>}</div>
  </div>;
}

