"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import { Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Alert } from "@/components/ui/alert";

type Option = { id: string; name: string };
type ProductDefaults = Partial<{ name: string; sku: string; categoryId: string; description: string; price: string | number; wholesalePrice: string | number | null; currency: string; unit: string; moq: number; stock: number; availabilityStatus: string; city: string; deliveryCities: string[]; leadTimeDays: number; imageUrl: string | null; isFeatured: boolean }>;

export function ProductForm({ endpoint, method = "POST", categories, cities, defaults = {}, companyId, redirectTo }: { endpoint: string; method?: "POST" | "PUT"; categories: Option[]; cities: Option[]; defaults?: ProductDefaults; companyId?: string; redirectTo: string }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [error, setError] = useState("");
  return (
    <form className="grid gap-6" onSubmit={async (event) => { event.preventDefault(); setPending(true); setError(""); const data = new FormData(event.currentTarget); const payload = { ...(companyId ? { companyId } : {}), name: data.get("name"), sku: data.get("sku"), categoryId: data.get("categoryId"), description: data.get("description"), price: Number(data.get("price")), wholesalePrice: data.get("wholesalePrice") ? Number(data.get("wholesalePrice")) : null, currency: data.get("currency"), unit: data.get("unit"), moq: Number(data.get("moq")), stock: Number(data.get("stock")), availabilityStatus: data.get("availabilityStatus"), city: data.get("city"), deliveryCities: String(data.get("deliveryCities")).split(",").map((item) => item.trim()).filter(Boolean), leadTimeDays: Number(data.get("leadTimeDays")), imageUrl: data.get("imageUrl"), isFeatured: data.get("isFeatured") === "on" }; const response = await fetch(endpoint, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); if (response.ok) { router.push(redirectTo); router.refresh(); } else setError(result.error?.message ?? "Не удалось сохранить товар"); setPending(false); }}>
      {error ? <Alert tone="danger">{error}</Alert> : null}
      <section className="surface-flat grid gap-4 p-5 sm:grid-cols-2"><h2 className="sm:col-span-2 font-extrabold">Основная информация</h2><label className="field-label">Название<input className="field" name="name" defaultValue={defaults.name} required /></label><label className="field-label">SKU<input className="field" name="sku" defaultValue={defaults.sku} required /></label><label className="field-label">Категория<select className="field" name="categoryId" defaultValue={defaults.categoryId} required><option value="">Выберите</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label className="field-label">Фото, URL<input className="field" type="url" name="imageUrl" defaultValue={defaults.imageUrl ?? ""} /></label><label className="field-label sm:col-span-2">Описание<textarea className="field min-h-36" name="description" defaultValue={defaults.description} minLength={30} required /></label></section>
      <section className="surface-flat grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-4"><h2 className="sm:col-span-2 lg:col-span-4 font-extrabold">Цена и склад</h2><label className="field-label">Цена<input className="field" type="number" name="price" min="1" step="0.01" defaultValue={defaults.price} required /></label><label className="field-label">Оптовая цена<input className="field" type="number" name="wholesalePrice" min="1" step="0.01" defaultValue={defaults.wholesalePrice ?? ""} /></label><label className="field-label">Валюта<select className="field" name="currency" defaultValue={defaults.currency ?? "KZT"}><option>KZT</option><option>USD</option></select></label><label className="field-label">Единица<select className="field" name="unit" defaultValue={defaults.unit ?? "PIECE"}>{[["KG","кг"],["LITER","л"],["PIECE","шт"],["BOX","короб"],["BAG","мешок"],["PACKAGE","упаковка"]].map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="field-label">MOQ<input className="field" type="number" name="moq" min="1" defaultValue={defaults.moq ?? 1} required /></label><label className="field-label">Остаток<input className="field" type="number" name="stock" min="0" defaultValue={defaults.stock ?? 0} required /></label><label className="field-label">Наличие<select className="field" name="availabilityStatus" defaultValue={defaults.availabilityStatus ?? "IN_STOCK"}><option value="IN_STOCK">В наличии</option><option value="LOW_STOCK">Мало</option><option value="OUT_OF_STOCK">Нет</option><option value="PRE_ORDER">Предзаказ</option></select></label><label className="field-label">Срок поставки, дней<input className="field" type="number" name="leadTimeDays" min="0" max="365" defaultValue={defaults.leadTimeDays ?? 1} required /></label></section>
      <section className="surface-flat grid gap-4 p-5 sm:grid-cols-2"><h2 className="sm:col-span-2 font-extrabold">Логистика</h2><label className="field-label">Город отгрузки<select className="field" name="city" defaultValue={defaults.city} required><option value="">Выберите</option>{cities.map((city) => <option key={city.id}>{city.name}</option>)}</select></label><label className="field-label">Города доставки, через запятую<input className="field" name="deliveryCities" defaultValue={defaults.deliveryCities?.join(", ")} required /></label><label className="flex items-center gap-2 text-sm font-semibold sm:col-span-2"><input type="checkbox" name="isFeatured" defaultChecked={defaults.isFeatured} />Рекомендуемый / featured товар</label></section>
      <div className="flex justify-end"><Button type="submit" disabled={pending}><Save className="size-4" />{pending ? "Сохраняем…" : "Сохранить товар"}</Button></div>
    </form>
  );
}

